## Text Analytics

Blog Link: https://www.analyticsvidhya.com/blog/2018/02/the-different-methods-deal-text-data-predictive-python/

In [1]:
import pandas as pd

In [2]:
cols=['sentiment','id','date','query_string','user','text']

In [19]:
df=pd.read_csv("../OtherData/trainingandtestdata/training.1600000.processed.noemoticon.csv",header=None,encoding='latin1',names=cols)

In [20]:
df.head()

,sentiment,id,date,query_string,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [21]:
df.sentiment.value_counts()

4    800000
0    800000
Name: sentiment, dtype: int64

In [22]:
df.drop(['id','date','query_string'],axis=1,inplace=True)

### Basic Feature Extraction

In [26]:
# number of words
df['word_count']=df['text'].apply(lambda x:len(str(x).split()))

In [27]:
df[['text','word_count']]

                                                      text  word_count
0        @switchfoot http://twitpic.com/2y1zl - Awww, t...          19
1        is upset that he can't update his Facebook by ...          21
2        @Kenichan I dived many times for the ball. Man...          18
3          my whole body feels itchy and like its on fire           10
4        @nationwideclass no, it's not behaving at all....          21
5                            @Kwesidei not the whole crew            5
6                                              Need a hug            3
7        @LOLTrish hey  long time no see! Yes.. Rains a...          22
8                     @Tatiana_K nope they didn't have it            6
9                                @twittera que me muera ?            5
10             spring break in plain city... it's snowing            7
11                              I just re-pierced my ears            5
12       @caregiving I couldn't bear to watch it.  And ...          20
13       @octolinz16 It it counts, idk why I did either...          15
14       @smarrison i would've been the first, but i di...          20
15       @iamjazzyfizzle I wish I got to watch it with ...          19
16       Hollis' death scene will hurt me severely to w...          18
17                                    about to file taxes            4
18       @LettyA ahh ive always wanted to see rent  lov...          11
19       @FakerPattyPattz Oh dear. Were you drinking ou...          12
20       @alydesigns i was out most of the day so didn'...          13
21       one of my friend called me, and asked to meet ...          20
22        @angry_barista I baked you a cake but I ated it           10
23                  this week is not going as i had hoped            9
24                              blagh class at 8 tomorrow            5
25          I hate when I have to call and wake people up           11
26       Just going to cry myself to sleep after watchi...          12
27                                  im sad now  Miss.Lilly           4
28       ooooh.... LOL  that leslie.... and ok I won't ...          17
29       Meh... Almost Lover is the exception... this t...          13
...                                                    ...         ...
1599970  Thanks @eastwestchic &amp; @wangyip Thanks! Th...          13
1599971  @marttn thanks Martin. not the most imaginativ...          13
1599972          @MikeJonesPhoto Congrats Mike  Way to go!           6
1599973  http://twitpic.com/7jp4n - OMG! Office Space.....           9
1599974  @yrclndstnlvr ahaha nooo you were just away fr...          25
1599975  @BizCoachDeb  Hey, I'm baack! And, thanks so m...          27
1599976  @mattycus Yeah, my conscience would be clear i...          10
1599977  @MayorDorisWolfe Thats my girl - dishing out t...           9
1599978                          @shebbs123 i second that            4
1599979                                     In the garden            3
1599980  @myheartandmind jo jen by nemuselo zrovna tÃ© ...          11
1599981  Another Commenting Contest! [;: Yay!!!  http:/...           6
1599982  @thrillmesoon i figured out how to see my twee...          26
1599983  @oxhot theri tomorrow, drinking coffee, talkin...          18
1599984  You heard it here first -- We're having a girl...          20
1599985  if ur the lead singer in a band, beware fallin...          19
1599986              @tarayqueen too much ads on my blog.            7
1599987  @La_r_a NEVEER  I think that you both will get...          14
1599988  @Roy_Everitt ha- good job. that's right - we g...          22
1599989                 @Ms_Hip_Hop im glad ur doing well            6
1599990                              WOOOOO! Xbox is back            4
1599991  @rmedina @LaTati Mmmm  That sounds absolutely ...          23
1599992                  ReCoVeRiNg FrOm ThE lOnG wEeKeNd            5
1599993                                  @SCOOBY_GRITBOYS            1
1599994  @Cliff_Forster Yeah, that does work better tha...          27
1599995  Just woke up. Having no school is the best fee...          11
1599996  TheWDB.com - Very cool to hear old Walt interv...          11
1599997  Are you ready for your MoJo Makeover? Ask me f...          11
1599998  Happy 38th Birthday to my boo of alll time!!! ...          12
1599999  happy #charitytuesday @theNSPCC @SparksCharity...           5

[1600000 rows x 2 columns]